const $=x=>document.getElementById(x),pick=a=>a[Math.floor(Math.random()*a.length)],cl=(v,a,b)=>Math.max(a,Math.min(b,v)),money=v=>(v<0?"-$":"$")+Math.abs(Math.round(v)).toLocaleString();
const P={college:{l:"COLLEGE",r:["Community College Student","Public University Student"],i:[4800,5700],c:55},military:{l:"MILITARY",r:["Junior Enlisted Service Member"],i:[7500,8250],c:64},trade:{l:"TRADE / APPRENTICESHIP",r:["Electrical Apprentice","HVAC Apprentice","Welding Trainee"],i:[7200,8100],c:66},workforce:{l:"WORKFORCE",r:["Warehouse Associate","Office Assistant","Medical Receptionist"],i:[6300,7200],c:48}};
const F=[["Single • No Children",0,72],["Single Parent • 1 Child (Age 2)",2040,61],["Partnered • 1 Child (Age 4)",1290,70],["Helps Support a Family Member",660,65]];
const D=[
["HOUSING","Where will you live?","Rent is only one cost. Commute, utilities, childcare access, privacy and reliability matter.",[["Live With Family",1260,{cash:-1260,savings:500,stability:6}],["Roommate Apartment",2370,{cash:-2370,stability:5,stress:2},"roommate"],["Apartment Alone",3720,{cash:-3720,stability:8,stress:-2}],["Cheap Studio Far Away",1830,{cash:-1830,stability:-4,stress:7},"cheapHousing"]]],
["TRANSPORTATION","How will you get where you need to go?","Reliability protects attendance, income, school progress and childcare.",[["Very Cheap Older Car",870,{cash:-870,stability:-7,stress:6},"cheapCar"],["Reliable Used Sedan",1830,{cash:-1830,stability:6,stress:-1},"usedCar"],["New Compact Car",2790,{cash:-2790,debt:14500,stability:9,stress:-2},"newCar"],["Transit + Rideshare",990,{cash:-990,stress:4},"transit"]]],
["CAR INSURANCE","Choose your auto protection.","Premium, deductible, coverage limits, vehicle value and legal requirements all matter.",[["Liability-Focused / Minimum Applicable",375,{cash:-375,protection:1,stability:-1},"liability"],["Balanced Coverage",615,{cash:-615,protection:8,stability:5},"fullAuto"],["High-Deductible Full Coverage",504,{cash:-504,protection:6,stability:3},"highDeduct"]]],
["HEALTH INSURANCE","Choose health coverage.","Compare premium, deductible, copays, prescriptions, network and emergency exposure.",[["Lower Premium / High Deductible",405,{cash:-405,protection:4,stability:1},"highMed"],["Standard Plan",735,{cash:-735,protection:9,stability:5},"med"],["Eligible Family Coverage",285,{cash:-285,protection:8,stability:5},"med"],["Go Uninsured",0,{protection:-14,stability:-6,stress:5},"uninsured"]]],
["CREDIT","Your laptop dies. You need one for work or school.","The smallest payment is not necessarily the cheapest decision.",[["Pay Cash",1000,{cash:-1000,stability:-5}],["Use Emergency Savings",0,{savings:-1000,stability:1}],["12-Month 0% Financing",85,{cash:-85,debt:915,credit:8,stability:2},"goodDebt"],["Easy Approval • 29.9% APR",55,{cash:-55,debt:1180,credit:-8,stability:-8,stress:8},"badDebt"]]],
["CHILD / FAMILY CARE","A dependent-care decision is required.","For parents this is childcare. Otherwise it represents care/support for someone depending on you.",[["Lowest-Cost Informal Care",960,{cash:-960,family:2,stability:-2,stress:4},"cheapCare"],["Licensed / Reliable Care",2280,{cash:-2280,family:9,stability:7,stress:-3},"goodCare"],["Adjust Hours / Split Care",1410,{cash:-1410,family:7,stability:4,stress:3},"splitCare"]]],
["MEDICAL EVENT","A medical problem requires treatment.","Your earlier health-insurance decision now matters.",null],
["CAREER","An opportunity could improve your future earnings.","Training costs money and time today. Staying comfortable can also have a cost.",[["Career Credential",850,{cash:-850,career:15,opportunity:15,stress:7},"credential"],["Do Nothing",0,{career:-3,opportunity:-5}],["Employer-Supported Training",420,{cash:-420,career:18,opportunity:17,stress:8},"credential"],["Extra Shifts Instead",-900,{cash:900,career:-2,opportunity:-6,stress:9}]]],
["THE FUTURE","You receive a $3,000 windfall.","Strengthen the life you built—or increase consumption.",[["Emergency Fund",3000,{cash:-3000,savings:3000,stability:10,stress:-4}],["Pay Down Debt",3000,{cash:-3000,debt:-3000,credit:10,stability:9}],["Career / Education Investment",3000,{cash:-3000,career:12,opportunity:15,stability:4}],["Lifestyle Upgrade",3000,{cash:-3000,stress:-7,stability:-2}]]]
];
let s,i=0,locked=false;
function start(path){let p=P[path],f=pick(F);s={path:p.l,role:pick(p.r),cash:pick(p.i)-f[1],savings:pick([250,500,850,1250,1900]),debt:pick([0,600,1400]),credit:pick([586,632,681,724]),career:p.c,family:f[2],protection:62,stability:65,stress:35,opportunity:60,familyDesc:f[0],tags:[]};$("start").classList.add("hide");$("game").classList.remove("hide");show()}
document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>start(b.dataset.p));
function score(){return Math.round(cl(50+Math.min(12,s.savings/600)-Math.min(18,s.debt/1800)+(s.credit-620)/14+(s.career-50)/5+(s.family-50)/6+(s.protection-50)/5+(s.stability-50)/4-s.stress/10+(s.opportunity-50)/6,0,100))}
function render(){$("path").textContent=s.path;$("role").textContent=s.role;$("family").textContent=s.familyDesc;let a=[["Cash",money(s.cash)],["Savings",money(s.savings)],["Debt",money(s.debt)],["Credit",s.credit],["Career",s.career],["Family",s.family],["Protection",s.protection],["Stability",s.stability],["Stress",s.stress],["Life Score",score()]];$("metrics").innerHTML=a.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
function med(){let t=new Set(s.tags),bill=t.has("med")?420:t.has("highMed")?1650:t.has("uninsured")?6200:1800;return [["Pay From Cash",bill,{cash:-bill,stress:5}],["Use Emergency Savings",0,{savings:-bill,stability:2,stress:3}],["Payment Plan",Math.round(bill*.12),{cash:-Math.round(bill*.12),debt:Math.round(bill*.88),stress:7}]]}
function show(){locked=false;render();if(i>=D.length){finish();return}let d=D[i],opts=d[3]||med();$("cat").textContent=`YEAR ${Math.min(5,Math.floor(i/2)+1)} • ${d[0]}`;$("q").textContent=d[1];$("ctx").textContent=d[2];$("opts").innerHTML=opts.map((o,j)=>`<button class="option" data-j="${j}"><div class="price">${o[1]<0?"+ "+money(-o[1]):o[1]===0?"$0 TODAY":money(o[1])}</div><h3>${o[0]}</h3><p>Think beyond today's price. This choice can affect later options.</p></button>`).join("");document.querySelectorAll("[data-j]").forEach(b=>b.onclick=()=>choose(opts[+b.dataset.j]))}
function apply(e){for(let[k,v]of Object.entries(e))if(typeof s[k]==="number")s[k]+=v;s.debt=Math.max(0,s.debt);s.savings=Math.max(0,s.savings);s.credit=cl(s.credit,300,850);["career","family","protection","stability","stress","opportunity"].forEach(k=>s[k]=cl(s[k],0,100))}
function choose(o){if(locked)return;locked=true;document.querySelectorAll("[data-j]").forEach(b=>b.disabled=true);apply(o[2]);if(o[3])s.tags.push(o[3]);let ev=null,t=new Set(s.tags);if(t.has("cheapCar")&&Math.random()<.55)ev=["BREAKDOWN BEFORE WORK","Your low-cost car needs an $860 repair and you miss part of a shift.",{cash:-860,stability:-9,stress:12,career:-3}];else if(t.has("uninsured")&&Math.random()<.5)ev=["UNINSURED MEDICAL COST","A routine emergency becomes a major financial problem.",{cash:-2800,debt:1900,protection:-8,stress:15,stability:-8}];else if(t.has("cheapCare")&&Math.random()<.5)ev=["CARE FALLS THROUGH","Care is canceled. You miss work and pay for emergency care.",{cash:-390,career:-4,family:-4,stress:12}];else if(t.has("badDebt")&&Math.random()<.5)ev=["CREDIT CONSEQUENCE","High-cost borrowing weakens your next application.",{credit:-24,stress:8,stability:-5}];if(ev)apply(ev[2]);$("rt").textContent=ev?ev[0]:"DECISION LOCKED";$("rx").textContent=ev?ev[1]:"Your choice is now part of your life. Some consequences may appear later.";$("result").classList.remove("hide");render()}
$("next").onclick=()=>{$("result").classList.add("hide");i++;show()};
function finish(){$("game").classList.add("hide");$("final").classList.remove("hide");let x=score();$("score").textContent=x;$("rank").textContent=x>=86?"STABLE & THRIVING":x>=72?"STABLE & GROWING":x>=58?"FUNCTIONING — BUT EXPOSED":x>=42?"ONE EMERGENCY FROM CRISIS":"CRISIS MODE";$("summary").textContent="Defend your life: strongest decision, costliest mistake, sacrifice that paid off, what you would change, and whether your life is sustainable."}
$("perf").onclick=()=>document.body.classList.toggle("performance");
